### ISSUE TITLE
Segmentation fault calling EventsLoop::new()

### ISSUE THREAD

**Issue by kvark** [tomaka/winit#232]
Kernel:
> Linux carbon 4.11.9-300.fc26.x86_64 #1 SMP

Roughly, started happening after I upgraded to Fedora 26.

Call stack:
```
Program received signal SIGSEGV, Segmentation fault.
0x00005555568f65bc in compiler_builtins::probestack::__rust_probestack ()
    at /checkout/src/rustc/compiler_builtins_shim/../../libcompiler_builtins/src/probestack.rs:55
55	/checkout/src/rustc/compiler_builtins_shim/../../libcompiler_builtins/src/probestack.rs: No such file or directory.
Missing separate debuginfos, use: dnf debuginfo-install bzip2-libs-1.0.6-22.fc26.x86_64 expat-2.2.1-1.fc26.x86_64 fontconfig-2.12.1-4.fc26.x86_64 freetype-2.7.1-9.fc26.x86_64 libX11-1.6.5-2.fc26.x86_64 libXau-1.0.8-7.fc26.x86_64 libXext-1.3.3-5.fc26.x86_64 libffi-3.1-12.fc26.x86_64 libgcc-7.1.1-3.fc26.x86_64 libglvnd-0.2.999-14.20170308git8e6e102.fc26.x86_64 libglvnd-glx-0.2.999-14.20170308git8e6e102.fc26.x86_64 libpng-1.6.28-2.fc26.x86_64 libxcb-1.12-3.fc26.x86_64 wayland-devel-1.13.0-1.fc26.x86_64 zlib-1.2.11-2.fc26.x86_64
(gdb) bt
#0  0x00005555568f65bc in compiler_builtins::probestack::__rust_probestack ()
    at /checkout/src/rustc/compiler_builtins_shim/../../libcompiler_builtins/src/probestack.rs:55
#1  0x00005555565810ce in lazy_static::lazy::{{impl}}::get::{{closure}}<[(&str, usize); 767],fn() -> [(&str, usize); 767]> ()
    at /home/kvark/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-0.2.8/src/lazy.rs:22
#2  0x000055555658097a in std::sync::once::{{impl}}::call_once::{{closure}}<closure> ()
    at /checkout/src/libstd/sync/once.rs:227
#3  0x00005555568ba13d in std::sync::once::Once::call_inner () at /checkout/src/libstd/sync/once.rs:307
#4  0x00005555565804fc in std::sync::once::Once::call_once<closure> (
    self=0x5555570ab4a8 <<x11_dl::xlib::Xlib::init::SYMS as core::ops::deref::Deref>::deref::__stability::LAZY+8>, f=...) at /checkout/src/libstd/sync/once.rs:227
#5  0x00005555565a32f0 in lazy_static::lazy::Lazy<[(&str, usize); 767]>::get<[(&str, usize); 767],fn() -> [(&str, usize); 767]> (self=<optimized out>)
    at /home/kvark/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-0.2.8/src/lazy.rs:22
#6  x11_dl::xlib::{{impl}}::init::{{impl}}::deref::__stability () at <__lazy_static_internal macros>:20
#7  x11_dl::xlib::{{impl}}::init::{{impl}}::deref (self=0x555556951e63 <str.eC>)
    at <__lazy_static_internal macros>:21
#8  0x00005555565a2c22 in x11_dl::xlib::Xlib::init (self=0x7ffffffe5810)
    at /home/kvark/.cargo/registry/src/github.com-1ecc6299db9ec823/x11-dl-2.14.0/src/link.rs:48
#9  0x00005555565a308d in x11_dl::xlib::Xlib::open ()
    at /home/kvark/.cargo/registry/src/github.com-1ecc6299db9ec823/x11-dl-2.14.0/src/link.rs:61
#10 0x0000555556545093 in winit::platform::platform::x11::xdisplay::XConnection::new (error_handler=...)
    at /home/kvark/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.5/src/platform/linux/x11/xdisplay---Type <return> to continue, or q <return> to quit---
.rs:29
#11 0x000055555654b626 in winit::platform::platform::{{impl}}::deref::__static_ref_initialize::x_backend ()
    at /home/kvark/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.5/src/platform/linux/mod.rs:44
#12 0x000055555654bcff in winit::platform::platform::{{impl}}::deref::__static_ref_initialize::{{closure}} ()
    at /home/kvark/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.5/src/platform/linux/mod.rs:67
#13 0x00005555564f9ab3 in core::result::Result<winit::platform::platform::UnixBackend, ()>::unwrap_or_else<winit::platform::platform::UnixBackend,(),closure> (self=..., op=...) at /checkout/src/libcore/result.rs:707
#14 0x000055555650abe6 in winit::platform::platform::{{impl}}::deref::__static_ref_initialize ()
    at /home/kvark/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.5/src/platform/linux/mod.rs:66
#15 core::ops::function::FnOnce::call_once<fn() -> winit::platform::platform::UnixBackend,()> ()
    at /checkout/src/libcore/ops/function.rs:143
#16 0x00005555564f7c7d in lazy_static::lazy::{{impl}}::get::{{closure}}<winit::platform::platform::UnixBackend,fn() -> winit::platform::platform::UnixBackend> ()
    at /home/kvark/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-0.2.8/src/lazy.rs:23
#17 0x00005555564f52aa in std::sync::once::{{impl}}::call_once::{{closure}}<closure> ()
    at /checkout/src/libstd/sync/once.rs:227
#18 0x00005555568ba13d in std::sync::once::Once::call_inner () at /checkout/src/libstd/sync/once.rs:307
#19 0x00005555564f521c in std::sync::once::Once::call_once<closure> (
    self=0x5555570ab438 <<winit::platform::platform::UNIX_BACKEND as core::ops::deref::Deref>::deref::__stability::LAZY+8>, f=...) at /checkout/src/libstd/sync/once.rs:227
#20 0x000055555654b5a0 in lazy_static::lazy::Lazy<winit::platform::platform::UnixBackend>::get<winit::platform::platform::UnixBackend,fn() -> winit::platform::platform::UnixBackend> (self=<optimized out>)
    at /home/kvark/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-0.2.8/src/lazy.rs:22
---Type <return> to continue, or q <return> to quit---
#21 winit::platform::platform::{{impl}}::deref::__stability () at <__lazy_static_internal macros>:20
#22 winit::platform::platform::{{impl}}::deref (self=0x55555694cbe5) at <__lazy_static_internal macros>:21
#23 0x00005555565498bb in winit::platform::platform::EventsLoop::new ()
    at /home/kvark/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.5/src/platform/linux/mod.rs:351
#24 0x000055555654a138 in winit::EventsLoop::new ()
    at /home/kvark/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.5/src/lib.rs:209
#25 0x0000555555a33733 in wrench::make_window (size=..., dp_ratio=..., vsync=false, headless=false)
    at src/main.rs:252
#26 0x0000555555a344f2 in wrench::main () at src/main.rs:321
```

**Comment by jwilm** [comment]
Which version of the compiler did you encounter this on?

**Comment by kvark** [comment]
rustc 1.20.0-nightly (bf0a9e0b4 2017-07-10)

**Comment by tomaka** [comment]
https://github.com/rust-lang/rust/issues/43102

**Comment by kvark** [comment]
Awesome, thanks!
