### ISSUE TITLE
XWayland no primary monitor panic

### ISSUE THREAD

**Issue by alexheretic** [tomaka/winit#317]
I got *panicked at '[winit] Failed to find the primary monitor'* this morning in a gnome 3.26 xwayland session.
```
...
   5:     0x55b950a664f6 - std::panicking::begin_panic::h697a7df9d6f5bf31
                               at /checkout/src/libstd/panicking.rs:538
   6:     0x55b950a616ce - winit::platform::platform::x11::monitor::get_primary_monitor::hf9d328fd4ff4d083
                               at /home/alex/project/winit/<panic macros>:3
   7:     0x55b950a61369 - winit::platform::platform::EventsLoop::get_primary_monitor::h4b1d199c535a7ed8
                               at /home/alex/project/winit/src/platform/linux/mod.rs:357
   8:     0x55b950a67f5e - winit::EventsLoop::get_primary_monitor::h701a7426af0bcdb9
                               at /home/alex/project/winit/src/lib.rs:210
```

It seems that this is somewhat correct, in that for some reason my sole monitor **XWAYLAND0** was not marked primary in xrandr. When I used xrandr to mark it primary manually this panic does not occur.

However, since `get_primary_monitor` does not return a `Result` this seems poor behaviour from winit from a user perspective.

I suggest we simply use the first available monitor as fallback for x11 primary not existing, or change this method return a `Result`.

**Comment by alexheretic** [comment]
I think #318 is a reasonable fix for this issue, as monitors can be connected with none primary as reported. 

*Or* perhaps we should always return an `Option<MonitorId>` to force explicit handling of this by winit consumers?
