### ISSUE TITLE
Panic when running glium example

### ISSUE THREAD

**Issue by palango** [tomaka/winit#429]
I'm getting the following error when running one of the simple glium demos (triangle) code on
`rustc 1.26.0-nightly (75af15ee6 2018-03-20)`.

I'm not sure if this is related to `winit´ but the stacktrace points here.

```
     Running `target/debug/test`
thread 'main' panicked at '~~~weak dyld: malformed executable '%s', skipping indirect symbol to %s
dyld: interposing %lu tuples onto: %s
dyld: dynamic interposing %lu tuples onto image: %s
dyld: dynamic interposing: at %p replace %p with %p in %s
/usr/lib/libgcc_s.1.dylibsequentialfree%18s %s 0x%0lX -> 0x%0lX for %s
bad rebase type %dmalformed rebase opcodes (%ld/%ld): address 0x%08lX is outside of segment %s (0x%08lX -> 0x%08lX)REBASE_OPCODE_SET_SEGMENT_AND_OFFS', /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.9.0/src/platform/macos/window.rs:348:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::begin_panic
             at libstd/panicking.rs:402
   5: std::panicking::try::do_call
             at libstd/panicking.rs:349
   6: winit::platform::platform::window::Window2::new
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.9.0/src/platform/macos/window.rs:348
   7: winit::platform::platform::Window::new
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.9.0/src/platform/macos/mod.rs:32
   8: <T as core::convert::From<T>>::from
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.9.0/src/window.rs:119
   9: glutin::platform::platform::Context::new
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.11.0/src/platform/macos/mod.rs:48
  10: <T as core::convert::From<T>>::from
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.11.0/src/lib.rs:322
  11: backtrace::symbolize::resolve
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.19.0/src/backend/glutin/mod.rs:70
  12: test::main
             at src/main.rs:10
  13: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  14: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  15: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:102
  16: std::io::Write::write_all
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  17: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  18: <test::main::Vertex as glium::vertex::Vertex>::build_bindings
[1]    65408 segmentation fault  RUST_BACKTRACE=1 cargo run
```

**Comment by palango** [comment]
As this works on stable, I created a bug at rust rust-lang/rust#49275

**Comment by palango** [comment]
Yes, works fine now.
