### ISSUE TITLE
Panic when using Fcitx5 input chinese

### ISSUE THREAD

**Issue by quininer** [tomaka/winit#440]
```
thread 'main' panicked at 'attempt to subtract with overflow', /home/quininer/workspace/ui/winit/src/platform/linux/x11/mod.rs:453:35
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'Failed to call XInternAtom (WM_PROTOCOLS): XError { description: "BadValue (integer parameter out of range for operation)", error_code: 2, request_code: 101, minor_code: 0 }', libcore/result.rs:945:5
stack backtrace:
   0:     0x55c1da1bda4b - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h89ba7da7562701ab
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55c1da1c2ac0 - std::sys_common::backtrace::print::h6c31ad9817780cde
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x55c1da1ba16d - std::panicking::default_hook::{{closure}}::h2058dd93a82247f5
                               at libstd/panicking.rs:207
   3:     0x55c1da1b9ecb - std::panicking::default_hook::h679f309f083c9814
                               at libstd/panicking.rs:223
   4:     0x55c1da1ba5bf - std::panicking::rust_panic_with_hook::hf996e11af0921186
                               at libstd/panicking.rs:402
   5:     0x55c1da1ba3e2 - std::panicking::begin_panic_fmt::h8164d62b26e4856a
                               at libstd/panicking.rs:349
   6:     0x55c1da1ba312 - rust_begin_unwind
                               at libstd/panicking.rs:325
   7:     0x55c1da201430 - core::panicking::panic_fmt::hdbf1954249c01b91
                               at libcore/panicking.rs:72
   8:     0x55c1da0d5b77 - core::result::unwrap_failed::h31ff2f70a7055851
                               at /checkout/src/libcore/macros.rs:26
   9:     0x55c1da0d429b - <core::result::Result<T, E>>::expect::h6409ca11a4445996
                               at /checkout/src/libcore/result.rs:809
  10:     0x55c1da09707f - <winit::platform::platform::x11::Window as core::ops::drop::Drop>::drop::h2ff265fd9c5889fb
                               at src/platform/linux/x11/mod.rs:1087
  11:     0x55c1da04bac4 - core::ptr::drop_in_place::h3a2f256af65c530f
                               at /checkout/src/libcore/ptr.rs:59
  12:     0x55c1da04b72f - core::ptr::drop_in_place::h1c4983e117d6cf94
                               at /checkout/src/libcore/ptr.rs:59
  13:     0x55c1da04cb34 - core::ptr::drop_in_place::h9fb6a3aefef6e214
                               at /checkout/src/libcore/ptr.rs:59
  14:     0x55c1da0593c7 - xim::main::ha55699d7099b253c
                               at examples/xim.rs:34
  15:     0x55c1da0543a1 - std::rt::lang_start::{{closure}}::ha4ff232e21bac6fb
                               at /checkout/src/libstd/rt.rs:74
  16:     0x55c1da1ba277 - std::panicking::try::do_call::hf0fdbf659d7b57b7
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:306
  17:     0x55c1da1c9c1e - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  18:     0x55c1da1b7cc5 - std::rt::lang_start_internal::hc1351a73a73f54f6
                               at libstd/panicking.rs:285
                               at libstd/panic.rs:361
                               at libstd/rt.rs:58
  19:     0x55c1da054381 - std::rt::lang_start::hc4156819566d16cc
                               at /checkout/src/libstd/rt.rs:74
  20:     0x55c1da05943d - main
  21:     0x7f427b478f49 - __libc_start_main
  22:     0x55c1da047259 - _start
  23:                0x0 - <unknown>
thread panicked while panicking. aborting.
fish: './target/debug/examples/xim' terminated by signal SIGILL (Illegal instruction)
```

This may be caused by https://github.com/tomaka/winit/pull/297.

**Comment by quininer** [comment]
Using release mode, it works. Because overflow checking is optimized.

But when using optirun, alacritty still panics.

```
[Unhandled CSI] action='t', args=[22, 0, 0], intermediates=[]
[Unhandled CSI] action='l', args=[1005], intermediates=[63]
[unhandled osc_dispatch]: [['5','0',],['C','u','r','s','o','r','S','h','a','p','e','=','0',],] at line 746
[unhandled osc_dispatch]: [['5','0',],['C','u','r','s','o','r','S','h','a','p','e','=','0',],] at line 746
[unhandled osc_dispatch]: [['5','0',],['C','u','r','s','o','r','S','h','a','p','e','=','0',],] at line 746
thread 'pty reader' panicked at 'Failed to call XSendEvent after wakeup: XError { description: "BadValue (integer parameter out of range for operation)", error_code: 2, request_code: 101, minor_code: 0 }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'Error sending shutdown to event loop: Disconnected', libcore/result.rs:945:5
```

**Comment by francesca64** [comment]
This is likely a duplicate of #366. Does PR #432 resolve this for you?

**Comment by quininer** [comment]
It fixes integer overflow, but still receives XError.

```
thread 'main' panicked at 'Failed to query pointer device: XError { description: "BadValue (integer parameter out of range for operation)", error_code: 2, request_code: 101, minor_code: 0 }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:72
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:809
  10: winit::platform::platform::x11::EventsLoop::process_event
             at ./winit/src/platform/linux/x11/mod.rs:712
  11: winit::platform::platform::x11::EventsLoop::run_forever
             at ./winit/src/platform/linux/x11/mod.rs:188
  12: winit::platform::platform::EventsLoop::run_forever
             at ./winit/src/platform/linux/mod.rs:415
  13: winit::EventsLoop::run_forever
             at ./winit/src/lib.rs:231
  14: test_winit_xim::main
             at src/main.rs:22
  15: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  16: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  18: std::rt::lang_start_internal
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  19: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  20: main
  21: __libc_start_main
  22: _start
```

I'm not quite sure what that means.

**Comment by francesca64** [comment]
The various `expect`s littered throughout the backend are applied to whatever the latest X error is, and since it's not called after every function, the messages can be misleading at times.

Fortunately, the [`request_code` field](https://www.x.org/wiki/Development/Documentation/Protocol/OpCodes/) should tell us what call actually caused the error, and it seems to be... `XGetKeyboardMapping`, which isn't ever directly called in winit's source code. However, rummaging through X11's source, it's called within `XKeycodeToKeysym`, `XKeysymToKeycode`, `XLookupKeysym`, `XRebindKeysym`, and `XLookupString`.

This will be tough to track down unless I can reproduce it. Can you verify that this is specifically an issue when using fcitx, as in, that it doesn't happen if you run with `XMODIFIERS="@im=none"`?

**Comment by quininer** [comment]
Yes, it works fine when don't use IME.

**Comment by quininer** [comment]
The backspace appears two consecutive times when using `x11-dead-keys` branch.

![small](https://user-images.githubusercontent.com/6286761/38185177-7dbcf62a-367f-11e8-9d21-69ad0cb7e56b.gif)

If run with `XMODIFIERS="@im=none"`, it will work fine.

**Comment by francesca64** [comment]
Good catch! Not only that, but the arrow keys are doubled as well. I've removed the filtering hack from that branch, so that shouldn't happen anymore.

For your other problem, is it possible that optirun is changing the environment the program is being run with in some way? (Assuming I'm correctly understanding that it only happens when using optirun)
```bash
diff --color <(fcitx-diagnose) <(optirun fcitx-diagnose)
```

**Comment by quininer** [comment]
There is no difference between the output of  `fcitx-diagnose` and `optirun fcitx-diagnose`.

**Comment by francesca64** [comment]
Unfortunately, I doubt #451 helps with this at all. I don't really have any ideas for how to proceed with this at the moment.

**Comment by quininer** [comment]
Unfortunately, it doesn't help.

**Comment by francesca64** [comment]
Can you give this branch a shot? https://github.com/francesca64/winit/tree/x11-cleanup-keysym

**Comment by francesca64** [comment]
I just remembered that Alacritty won't build on winit 0.13, so here's an Alacritty branch you can try: https://github.com/francesca64/alacritty/tree/x11-keysym

**Comment by quininer** [comment]
It's still error. I found it panic when switching windows.

```
    Finished dev [unoptimized + debuginfo] target(s) in 2.62 secs                                                                                                                      [0/1716]
     Running `target/debug/examples/window`
XInternAtom name:"WM_DELETE_WINDOW" atom:311
XInternAtoms atoms:[401, 392, 395, 396, 393, 394, 406, 400, 397, 398, 603, 1551]
XInternAtom name:"XIM_SERVERS" atom:527
XGetWindowProperty prop:527 fmt:64 len:00 off:1024 out:01, buf:[526]
XInternAtom name:"_NET_SUPPORTED" atom:344
XGetWindowProperty prop:344 fmt:64 len:00 off:1024 out:68, buf:[344, 386, 442, 443, 444, 445, 447, 448, 389, 346, 449, 451, 452, 450, 348, 347, 349, 453, 455, 366, 380, 367, 368, 369, 370, 373, 371, 372, 381, 354, 360, 359, 358, 467, 468, 469, 470, 357, 355, 356, 362, 361, 456, 457, 458, 351, 352, 313, 363, 460, 462, 461, 472, 473, 474, 475, 477, 478, 479, 480, 481, 383, 382, 484, 365, 487, 489, 463]
XInternAtom name:"_NET_SUPPORTING_WM_CHECK" atom:386
XInternAtom name:"_NET_WM_NAME" atom:349
XGetWindowProperty prop:386 fmt:64 len:00 off:1024 out:01, buf:[35651590]
XGetWindowProperty prop:386 fmt:64 len:00 off:1024 out:01, buf:[35651590]
XInternAtom name:"UTF8_STRING" atom:391
XGetWindowProperty prop:349 fmt:08 len:00 off:1024 out:04, buf:[75, 87, 105, 110]
XSync
XSync
XSync
XSync
XSync
XSync
XSync
XSync
XSync
XChangeProperty prop:349 val:[65, 32, 102, 97, 110, 116, 97, 115, 116, 105, 99, 32, 119, 105, 110, 100, 111, 119, 33, 0]
XInternAtom name:"_MOTIF_WM_HINTS" atom:339
XChangeProperty prop:339 val:[2, 0, 1, 0, 0]
XInternAtom name:"XdndAware" atom:401
XChangeProperty prop:401 val:[5]
XInternAtom name:"_NET_WM_STATE_MAXIMIZED_HORZ" atom:358
XInternAtom name:"_NET_WM_STATE_MAXIMIZED_VERT" atom:359
XInternAtom name:"_NET_WM_STATE" atom:354
XInternAtom name:"_NET_WM_STATE_FULLSCREEN" atom:357
XSync
XGetWindowProperty prop:344 fmt:64 len:00 off:1024 out:68, buf:[344, 386, 442, 443, 444, 445, 447, 448, 389, 346, 449, 451, 452, 450, 348, 347, 349, 453, 455, 366, 380, 367, 368, 369, 370, 373, 371, 372, 381, 354, 360, 359, 358, 467, 468, 469, 470, 357, 355, 356, 362, 361, 456, 457, 458, 351, 352, 313, 363, 460, 462, 461, 472, 473, 474, 475, 477, 478, 479, 480, 481, 383, 382, 484, 365, 487, 489, 463]
XGetWindowProperty prop:386 fmt:64 len:00 off:1024 out:01, buf:[35651590]
XGetWindowProperty prop:386 fmt:64 len:00 off:1024 out:01, buf:[35651590]
XGetWindowProperty prop:349 fmt:08 len:00 off:1024 out:04, buf:[75, 87, 105, 110]
XTranslateCoordinates coords:TranslatedCoords { x_rel_root: 0, y_rel_root: 29, child: 35651615 }
XGetGeometry geo:Geometry { root: 392, x_rel_parent: 0, y_rel_parent: 0, width: 1024, height: 768, border: 0, depth: 24 }
XInternAtom name:"_NET_CLIENT_LIST" atom:442
XGetWindowProperty prop:442 fmt:64 len:00 off:1024 out:09, buf:[10485774, 10485801, 56623105, 65011733, 75497475, 77594627, 56623129, 56623138, 73400324]
XInternAtom name:"_NET_FRAME_EXTENTS" atom:383
XGetWindowProperty prop:383 fmt:64 len:00 off:1024 out:04, buf:[0, 0, 29, 0]
thread 'main' panicked at 'Failed to unfocus input context: XError { description: "BadValue (integer parameter out of range for operation)", error_code: 2, request_code: 101, minor_code: 0 }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by quininer** [comment]
Related https://github.com/jwilm/alacritty/issues/1038#issuecomment-358713797
