### ISSUE TITLE
Linux panic: "Library libwayland-client.so could not be loaded."

### ISSUE THREAD

**Issue by b-r-u** [tomaka/winit#504]
Running the window example results in a panic on Debian 8.10 (jessie) with the X11 and the Wayland backend:

```shell
$ cargo run --example window
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/window`
thread 'main' panicked at 'Library libwayland-client.so could not be loaded.', libcore/option.rs:916:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
This happens since this commit https://github.com/tomaka/winit/commit/1e971030946a289eec598c0c40bff6ec8ba1190f

Here is the relevant backtrace:
```shell
   8: core::option::expect_failed
             at libcore/option.rs:916
   9: <core::option::Option<T>>::expect
             at /checkout/src/libcore/option.rs:302
  10: core::ops::function::FnOnce::call_once
             at .multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-sys-0.20.3/src/client.rs:110
             at /checkout/src/libcore/ops/function.rs:223
  11: <lazy_static::lazy::Lazy<T>>::get::{{closure}}
             at .multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.0.0/src/lazy.rs:24
  12: std::sync::once::Once::call_once::{{closure}}
             at /checkout/src/libstd/sync/once.rs:227
  13: std::sync::once::Once::call_inner
             at libstd/sync/once.rs:340
  14: std::sync::once::Once::call_once
             at /checkout/src/libstd/sync/once.rs:227
  15: <wayland_sys::client::WAYLAND_CLIENT_HANDLE as core::ops::deref::Deref>::deref
             at .multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.0.0/src/lazy.rs:23
             at .multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-sys-0.20.3/<__lazy_static_internal macros>:13
             at .multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-sys-0.20.3/<__lazy_static_internal macros>:14
  16: wayland_client::display::Display::connect_to_env
             at .multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.20.3/src/display.rs:106
  17: winit::platform::platform::wayland::event_loop::EventsLoop::new
             at src/platform/linux/wayland/event_loop.rs:104
  18: winit::platform::platform::EventsLoop::new_wayland
             at src/platform/linux/mod.rs:399
  19: winit::platform::platform::EventsLoop::new
             at src/platform/linux/mod.rs:377
  20: winit::EventsLoop::new
             at src/lib.rs:200
  21: window::main
             at examples/window.rs:4
```

**Comment by vberger** [comment]
This should be fixed by the release of wayland-client 0.20.4. Can you confirm that `cargo update` fixes it?

**Comment by b-r-u** [comment]
Thanks for updating! The panic disappears with `cargo update`. Should `Cargo.toml` be updated accordingly?

This also means that the Wayland backend is now dysfunctional on Debian 8.10, but this probably should be another issue.

**Comment by vberger** [comment]
According to the error, it looks like the Wayland libraries are not installed on your system. Likely because Debian has not yet made the migration to Wayland, and you are still using X11. So unless you were specifically trying to use a Wayland compositor, this is normal.

We could bump the version in Cargo.toml to avoid anybody to tumble on this again, indeed.

**Comment by vberger** [comment]
> `libwayland-client.so` is present on my system, but I guess that its version is so old that some expected symbols are missing and dlopen fails because of that.

Ah yes, that is possible, wayland-client requires at least the version 1.12 of the wayland libs (which was released on september 2016).

**Comment by francesca64** [comment]
Should we document that?

**Comment by vberger** [comment]
We might want do document that, though that's relatively minor thanks to the x11 fallback I guess.
